@startuml

class RampMeterController {
}

abstract class Sensor {
}

Sensor <|-- FreewaySensor
Sensor <|-- DemandSensor
Sensor <|-- PassageSensor
Sensor <|-- EndOfQueueSensor

class FreewaySensor {
}
class DemandSensor {
}
class PassageSensor {
}
class EndOfQueueSensor {
}

class RampTrafficLight {
lightState
changeLight()
}

@enduml