@startuml
skinparam classAttributeIconSize 0

enum Color {
RED
GREEN
}

class RampMeterController {
-sensors: Sensor*[]
/-meteringRate: number
+update()
+processSensorData()
+setMeteringRate(r: number)
+getMeteringRate()
}

class RampTrafficLight {
-currentColor: Color
+setLightColor(c: Color)
+getLightColor()
}

class WarningSignal {
-isOn: boolean
+setSignalState(s: boolean)
+getSignalState()
}

abstract class Sensor {
-sensorStatus: boolean
+setStatus(s: boolean)
+getStatus()
+notifyController()
}

class FreewaySensor {
}
class DemandSensor {
}
class PassageSensor {
}
class EndOfQueueSensor {
}

Sensor <|-- FreewaySensor
Sensor <|-- DemandSensor
Sensor <|-- PassageSensor
Sensor <|-- EndOfQueueSensor

RampMeterController "1" -- "4..*" Sensor : send data <

RampMeterController "1" -- "1" RampTrafficLight : change state >
RampMeterController "1" -- "1" WarningSignal : change state >

@enduml