@startuml

'subregex for req 6:
'DS ON (\d+)\n((?!DS OFF \1\n(.|\n)*PS ON \1\n)(.|\n))*PS OFF \1\n


[*] --> S1
S1 --> S2: DS ON x\\n
S1 --> S1: else

S2 --> S2: else
S2 --> S3: DS OFF x\\n
S3 --> S4: PS ON x\\n
S3 --> S3: else

S4 --> S1: PS OFF x\\n
S4 --> S4: else

S3 --> [*]: PS OFF x\\n

S2 --> [*]: PS OFF x\\n|PS ON x\\n

@enduml
