@startuml

'5) When the FS is ON and the QS is ON,
'if DS is turned ON, it indicates intense traffic over the ramp.
'In this scenario, two cars must cross the TL before it turns RED.
'Then, set TL to GREEN. After DS is OFF, ON and OFF (two cars),
'turn TL to RED.

title "Sequence diagram for requirement 5"

actor Car1 as Car1
actor Car2 as Car2

control RMController as RMC
entity RampTrafficLight as RTL
entity EndOfQueueSensor as QS
entity DemandSensor as DS
entity PassageSensor as PS


note left of Car1: Preconditions:\n\t FreewaySensor turned ON\n\t EndOfQueueSensor turned ON\n\t DemandSensor is ON\n\t RampTrafficLight is RED\n\t PassageSensor is turned OFF

'below commented lines not explicitly needed because they are part of the preconditions
'FS -> RMC: on
'QS -> RMC: on
'DS -> RMC: on

note over RMC: Preconditions are met
RMC -> RTL: Tell the RTL to turn GREEN


Car1 -> DS: Leaves the sensor Demand Sensor area
DS -> RMC: Notify RMC that the sensor turned OFF

alt main success scenario
    Car1 -> PS: Enters the Passage Sensor area
    PS -> RMC: Notify RMC that the sensor turned ON
    Car1 -> PS: Leaves the Passage Sensor area
    PS -> RMC: Notify RMC that the sensor turned OFF
    Car2 -> DS: enters the Demand Sensor area
    DS -> RMC: Notify RMC that the sensor turned ON
else alternative scenario 1
    Car2 -> DS: Enters the Demand Sensor area
    DS -> RMC: Notify RMC that the sensor turned ON
    Car1 -> PS: Enters the Passage Sensor area
    PS -> RMC: Notify RMC that the sensor turned ON
    Car1 -> PS: Leaves the Passage Sensor area
    PS -> RMC: Notify RMC that the sensor turned OFF
else alternative scenario 2
    Car1 -> PS: Enters the Passage Sensor area
    PS -> RMC: Notify RMC that the sensor turned ON
    Car2 -> DS: Enters the Demand Sensor area
    DS -> RMC: Notify RMC that the sensor turned ON
    Car1 -> PS: Leaves the Passage Sensor area
    PS -> RMC: Notify RMC that the sensor turned OFF
end


Car2 -> DS: Leaves the Demand Sensor area
DS -> RMC: Notify RMC that the sensor turned OFF

RMC -> RTL: Tell the RTL that it has to turn the right RED

note left of Car1: Postconditions:\n\t PassageSensor turned ON \n\t and then PassageSensor \n\t\t turned OFF\n\t

@enduml