@startuml

'5) When the FS is ON and the QS is ON,
'if DS is turned ON, it indicates intense traffic over the ramp.
'In this scenario, two cars must cross the TL before it turns RED.
'Then, set TL to GREEN. After DS is OFF, ON and OFF (two cars),
'turn TL to RED.

title "Sequence diagram for requirement 5"

note across: preconditions per entity for all entities

control RMController as RMC
entity FreewaySensor as FS
entity EndOfQueueSensor as QS
entity DemandSensor as DS
entity RampTrafficLight as RTL

'note over FS : Preconditions:\n\t Turned OFF
'note over QS : Preconditions:\n\t Turned ON
'note over DS : Preconditions:\n\t Turned ON


FS -> RMC: on
QS -> RMC: on
DS -> RMC: on

RMC -> RTL: GREEN

DS -> RMC: off
DS -> RMC: on
DS -> RMC: off

RMC -> RTL: RED

note across: postconditions per entity for all entities

@enduml