@startuml
autonumber

'6) The passage sensor can only be turned ON once a car leaves the demand
'sensor shifting from ON to OFF. Another car can only turn the
'passage sensor ON once it has been turned OFF (the previous car joined the mainline).

entity PassageSensor as PS
entity DemandSensor as DS
control RMController as RMC

note left of PS : Preconditions:\n\t PassageSensor turned OFF \n\t DemandSensor turned ON

DS -> RMC : OFF
PS -> RMC : ON
PS -> RMC : OFF

note left of PS : Postconditions:\n\t PassageSensor turned OFF \n\t

@enduml