@startuml

'5) When the FS is ON and the QS is ON,
'if DS is turned ON, it indicates intense traffic over the ramp.
'In this scenario, two cars must cross the TL before it turns RED.
'Then, set TL to GREEN. After DS is OFF, ON and OFF (two cars),
'turn TL to RED.

title "Sequence diagram for requirement 5"

control RMController as RMC
entity FreewaySensor
entity EndOfQueueSensor
entity DemandSensor
entity RampTrafficLight

FreewaySensor -> RMC: on
EndOfQueueSensor -> RMC: on
DemandSensor -> RMC: on

DemandSensor -> RMC: off
DemandSensor -> RMC: on
DemandSensor -> RMC: off

group . [pre: RampTrafficLight.color == GREEN]
    RMC -> RampTrafficLight: setLightColor(RED)
end


@enduml