@startuml

'6) The passage sensor can only be turned ON once a car leaves the demand
'sensor shifting from ON to OFF. Another car can only turn the
'passage sensor ON once it has been turned OFF (the previous car joined the mainline).
title "Sequence diagram for requirement 6"

actor Car as Car
entity PassageSensor as PS
entity DemandSensor as DS
control RMController as RMC

note left of Car : Preconditions:\n\t PassageSensor turned OFF \n\t DemandSensor turned ON

Car -> DS:Leaves Demand Sensor area
DS -> RMC : Notify the RMC that the demand sensor is OFF
Car -> DS:Enters Passage Sensor area
PS -> RMC : Notify the RMC that the passage sensor is ON
Car -> PS :Car leaves the demand sensor
PS -> RMC : Notify the RMC that the passage sensor is OFF

note left  of Car : Postconditions:\n\t PassageSensor turned OFF \n\t

@enduml