"""Implementation of statechart c.
Generated by itemis CREATE code generator.
"""

import queue
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))

class C:
	"""Implementation of the state machine C.
	"""

	class State:
		""" State Enum
		"""
		(
			main_region_temp,
			main_region_zero,
			main_region_one,
			main_region_initial,
			null_state
		) = range(5)
	
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		
		self.x = None
		
		self.in_event_queue = queue.Queue()
		# enumeration of all states:
		self.__State = C.State
		self.__state_conf_vector_changed = None
		self.__state_vector = [None] * 1
		for __state_index in range(1):
			self.__state_vector[__state_index] = self.State.null_state
		
		# for timed statechart:
		self.timer_service = None
		self.__time_events = [None] * 1
		
		# initializations:
		#Default init sequence for statechart C
		self.x = 0
		self.__is_executing = False
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.main_region_temp:
			return self.__state_vector[0] == self.__State.main_region_temp
		if s == self.__State.main_region_zero:
			return self.__state_vector[0] == self.__State.main_region_zero
		if s == self.__State.main_region_one:
			return self.__state_vector[0] == self.__State.main_region_one
		if s == self.__State.main_region_initial:
			return self.__state_vector[0] == self.__State.main_region_initial
		return False
		
	def time_elapsed(self, event_id):
		"""Add time events to in event queue
		"""
		if event_id in range(1):
			self.in_event_queue.put(lambda: self.raise_time_event(event_id))
			self.run_cycle()
	
	def raise_time_event(self, event_id):
		"""Raise timed events using the event_id.
		"""
		self.__time_events[event_id] = True
	
	def __execute_queued_event(self, func):
		func()
	
	def __get_next_event(self):
		if not self.in_event_queue.empty():
			return self.in_event_queue.get()
		return None
	
	def __entry_action_main_region_initial(self):
		"""Entry action for state 'Initial'..
		"""
		#Entry action for state 'Initial'.
		self.timer_service.set_timer(self, 0, (1 * 1000), False)
		
	def __exit_action_main_region_initial(self):
		"""Exit action for state 'Initial'..
		"""
		#Exit action for state 'Initial'.
		self.timer_service.unset_timer(self, 0)
		
	def __enter_sequence_main_region_temp_default(self):
		"""'default' enter sequence for state Temp.
		"""
		#'default' enter sequence for state Temp
		self.__state_vector[0] = self.State.main_region_temp
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_zero_default(self):
		"""'default' enter sequence for state Zero.
		"""
		#'default' enter sequence for state Zero
		self.__state_vector[0] = self.State.main_region_zero
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_one_default(self):
		"""'default' enter sequence for state One.
		"""
		#'default' enter sequence for state One
		self.__state_vector[0] = self.State.main_region_one
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_initial_default(self):
		"""'default' enter sequence for state Initial.
		"""
		#'default' enter sequence for state Initial
		self.__entry_action_main_region_initial()
		self.__state_vector[0] = self.State.main_region_initial
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_default(self):
		"""'default' enter sequence for region main region.
		"""
		#'default' enter sequence for region main region
		self.__react_main_region__entry_default()
		
	def __exit_sequence_main_region_temp(self):
		"""Default exit sequence for state Temp.
		"""
		#Default exit sequence for state Temp
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region_zero(self):
		"""Default exit sequence for state Zero.
		"""
		#Default exit sequence for state Zero
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region_one(self):
		"""Default exit sequence for state One.
		"""
		#Default exit sequence for state One
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region_initial(self):
		"""Default exit sequence for state Initial.
		"""
		#Default exit sequence for state Initial
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region_initial()
		
	def __exit_sequence_main_region(self):
		"""Default exit sequence for region main region.
		"""
		#Default exit sequence for region main region
		state = self.__state_vector[0]
		if state == self.State.main_region_temp:
			self.__exit_sequence_main_region_temp()
		elif state == self.State.main_region_zero:
			self.__exit_sequence_main_region_zero()
		elif state == self.State.main_region_one:
			self.__exit_sequence_main_region_one()
		elif state == self.State.main_region_initial:
			self.__exit_sequence_main_region_initial()
		
	def __react_main_region__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_initial_default()
		
	def __react(self, transitioned_before):
		"""Implementation of __react function.
		"""
		#State machine reactions.
		return transitioned_before
	
	
	def __main_region_temp_react(self, transitioned_before):
		"""Implementation of __main_region_temp_react function.
		"""
		#The reactions of state Temp.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.x == 0:
				self.__exit_sequence_main_region_temp()
				self.__enter_sequence_main_region_zero_default()
				self.__react(0)
				transitioned_after = 0
			elif self.x == 1:
				self.__exit_sequence_main_region_temp()
				self.__enter_sequence_main_region_one_default()
				self.__react(0)
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = self.__react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_zero_react(self, transitioned_before):
		"""Implementation of __main_region_zero_react function.
		"""
		#The reactions of state Zero.
		transitioned_after = transitioned_before
		#Always execute local reactions.
		transitioned_after = self.__react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_one_react(self, transitioned_before):
		"""Implementation of __main_region_one_react function.
		"""
		#The reactions of state One.
		transitioned_after = transitioned_before
		#Always execute local reactions.
		transitioned_after = self.__react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_initial_react(self, transitioned_before):
		"""Implementation of __main_region_initial_react function.
		"""
		#The reactions of state Initial.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__time_events[0]:
				self.__exit_sequence_main_region_initial()
				self.x = self.x + 1
				self.__time_events[0] = False
				self.__enter_sequence_main_region_temp_default()
				self.__react(0)
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = self.__react(transitioned_before)
		return transitioned_after
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.__time_events[0] = False
	
	
	def __micro_step(self):
		"""Implementation of __micro_step function.
		"""
		state = self.__state_vector[0]
		if state == self.State.main_region_temp:
			self.__main_region_temp_react(-1)
		elif state == self.State.main_region_zero:
			self.__main_region_zero_react(-1)
		elif state == self.State.main_region_one:
			self.__main_region_one_react(-1)
		elif state == self.State.main_region_initial:
			self.__main_region_initial_react(-1)
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		#Performs a 'run to completion' step.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		next_event = self.__get_next_event()
		if next_event is not None:
			self.__execute_queued_event(next_event)
		condition_0 = True
		while condition_0:
			self.__micro_step()
			self.__clear_in_events()
			condition_0 = False
			next_event = self.__get_next_event()
			if next_event is not None:
				self.__execute_queued_event(next_event)
				condition_0 = True
		self.__is_executing = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		#Activates the state machine.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default enter sequence for statechart C
		self.__enter_sequence_main_region_default()
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		#Deactivates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default exit sequence for statechart C
		self.__exit_sequence_main_region()
		self.__is_executing = False
	
	
	def trigger_without_event(self):
		"""Implementation of triggerWithoutEvent function.
		"""
		self.run_cycle()
	
