"""Implementation of statechart statechart.
Generated by itemis CREATE code generator.
"""

import queue
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))
from yakindu.rx import Observable

class Statechart:
	"""Implementation of the state machine Statechart.
	"""

	class State:
		""" State Enum
		"""
		(
			main_region_red,
			main_region_green,
			main_region_yellow,
			null_state
		) = range(4)
	
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		
		self.button_pressed = None
		self.button_released = None
		self.car_detected = None
		self.set_led = None
		self.set_led_value = None
		self.set_led_observable = Observable()
		self.set_red = None
		self.set_red_value = None
		self.set_red_observable = Observable()
		self.set_green = None
		self.set_green_value = None
		self.set_green_observable = Observable()
		self.set_yellow = None
		self.set_yellow_value = None
		self.set_yellow_observable = Observable()
		
		self.__internal_event_queue = queue.Queue()
		self.in_event_queue = queue.Queue()
		self.local_set_led = None
		self.local_set_led_value = None
		
		# enumeration of all states:
		self.__State = Statechart.State
		self.__state_conf_vector_changed = None
		self.__state_vector = [None] * 1
		for __state_index in range(1):
			self.__state_vector[__state_index] = self.State.null_state
		
		# for timed statechart:
		self.timer_service = None
		self.__time_events = [None] * 4
		
		# initializations:
		self.__is_executing = False
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.main_region_red:
			return self.__state_vector[0] == self.__State.main_region_red
		if s == self.__State.main_region_green:
			return self.__state_vector[0] == self.__State.main_region_green
		if s == self.__State.main_region_yellow:
			return self.__state_vector[0] == self.__State.main_region_yellow
		return False
		
	def time_elapsed(self, event_id):
		"""Add time events to in event queue
		"""
		if event_id in range(4):
			self.in_event_queue.put(lambda: self.raise_time_event(event_id))
			self.run_cycle()
	
	def raise_time_event(self, event_id):
		"""Raise timed events using the event_id.
		"""
		self.__time_events[event_id] = True
	
	def __execute_queued_event(self, func):
		func()
	
	def __get_next_event(self):
		if not self.__internal_event_queue.empty():
			return self.__internal_event_queue.get()
		if not self.in_event_queue.empty():
			return self.in_event_queue.get()
		return None
	
	
	def raise_local_set_led(self, value):
		"""Raise method for event local_set_led.
		"""
		self.__internal_event_queue.put(lambda: self.__raise_local_set_led_call(value))
	
	def __raise_local_set_led_call(self, value):
		"""Raise callback for event local_set_led.
		"""
		self.local_set_led = True
		self.local_set_led_value = value
	
	def raise_button_pressed(self):
		"""Raise method for event button_pressed.
		"""
		self.in_event_queue.put(self.__raise_button_pressed_call)
		self.run_cycle()
	
	def __raise_button_pressed_call(self):
		"""Raise callback for event button_pressed.
		"""
		self.button_pressed = True
	
	def raise_button_released(self):
		"""Raise method for event button_released.
		"""
		self.in_event_queue.put(self.__raise_button_released_call)
		self.run_cycle()
	
	def __raise_button_released_call(self):
		"""Raise callback for event button_released.
		"""
		self.button_released = True
	
	def raise_car_detected(self):
		"""Raise method for event car_detected.
		"""
		self.in_event_queue.put(self.__raise_car_detected_call)
		self.run_cycle()
	
	def __raise_car_detected_call(self):
		"""Raise callback for event car_detected.
		"""
		self.car_detected = True
	
	def __entry_action_main_region_red(self):
		"""Entry action for state 'red'..
		"""
		#Entry action for state 'red'.
		self.timer_service.set_timer(self, 0, (2 * 1000), False)
		self.timer_service.set_timer(self, 1, (1 * 1000), False)
		self.set_red_observable.next(True)
		
	def __entry_action_main_region_green(self):
		"""Entry action for state 'green'..
		"""
		#Entry action for state 'green'.
		self.timer_service.set_timer(self, 2, (2 * 1000), False)
		self.set_green_observable.next(True)
		self.set_led_observable.next(True)
		self.raise_local_set_led(True)
		
	def __entry_action_main_region_yellow(self):
		"""Entry action for state 'yellow'..
		"""
		#Entry action for state 'yellow'.
		self.timer_service.set_timer(self, 3, (1 * 1000), False)
		self.set_yellow_observable.next(True)
		
	def __exit_action_main_region_red(self):
		"""Exit action for state 'red'..
		"""
		#Exit action for state 'red'.
		self.timer_service.unset_timer(self, 0)
		self.timer_service.unset_timer(self, 1)
		
	def __exit_action_main_region_green(self):
		"""Exit action for state 'green'..
		"""
		#Exit action for state 'green'.
		self.timer_service.unset_timer(self, 2)
		
	def __exit_action_main_region_yellow(self):
		"""Exit action for state 'yellow'..
		"""
		#Exit action for state 'yellow'.
		self.timer_service.unset_timer(self, 3)
		
	def __enter_sequence_main_region_red_default(self):
		"""'default' enter sequence for state red.
		"""
		#'default' enter sequence for state red
		self.__entry_action_main_region_red()
		self.__state_vector[0] = self.State.main_region_red
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_green_default(self):
		"""'default' enter sequence for state green.
		"""
		#'default' enter sequence for state green
		self.__entry_action_main_region_green()
		self.__state_vector[0] = self.State.main_region_green
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_yellow_default(self):
		"""'default' enter sequence for state yellow.
		"""
		#'default' enter sequence for state yellow
		self.__entry_action_main_region_yellow()
		self.__state_vector[0] = self.State.main_region_yellow
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_default(self):
		"""'default' enter sequence for region main region.
		"""
		#'default' enter sequence for region main region
		self.__react_main_region__entry_default()
		
	def __exit_sequence_main_region_red(self):
		"""Default exit sequence for state red.
		"""
		#Default exit sequence for state red
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region_red()
		
	def __exit_sequence_main_region_green(self):
		"""Default exit sequence for state green.
		"""
		#Default exit sequence for state green
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region_green()
		
	def __exit_sequence_main_region_yellow(self):
		"""Default exit sequence for state yellow.
		"""
		#Default exit sequence for state yellow
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region_yellow()
		
	def __exit_sequence_main_region(self):
		"""Default exit sequence for region main region.
		"""
		#Default exit sequence for region main region
		state = self.__state_vector[0]
		if state == self.State.main_region_red:
			self.__exit_sequence_main_region_red()
		elif state == self.State.main_region_green:
			self.__exit_sequence_main_region_green()
		elif state == self.State.main_region_yellow:
			self.__exit_sequence_main_region_yellow()
		
	def __react_main_region__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_red_default()
		
	def __react(self, transitioned_before):
		"""Implementation of __react function.
		"""
		#State machine reactions.
		return transitioned_before
	
	
	def __main_region_red_react(self, transitioned_before):
		"""Implementation of __main_region_red_react function.
		"""
		#The reactions of state red.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__time_events[0]:
				self.__exit_sequence_main_region_red()
				self.__time_events[0] = False
				self.__enter_sequence_main_region_green_default()
				self.__react(0)
				transitioned_after = 0
			elif (self.__time_events[1]) and (self.local_set_led_value):
				self.__exit_sequence_main_region_red()
				self.__time_events[1] = False
				self.__enter_sequence_main_region_red_default()
				self.__react(0)
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = self.__react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_green_react(self, transitioned_before):
		"""Implementation of __main_region_green_react function.
		"""
		#The reactions of state green.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__time_events[2]:
				self.__exit_sequence_main_region_green()
				self.__time_events[2] = False
				self.__enter_sequence_main_region_yellow_default()
				self.__react(0)
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = self.__react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_yellow_react(self, transitioned_before):
		"""Implementation of __main_region_yellow_react function.
		"""
		#The reactions of state yellow.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__time_events[3]:
				self.__exit_sequence_main_region_yellow()
				self.__time_events[3] = False
				self.__enter_sequence_main_region_red_default()
				self.__react(0)
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = self.__react(transitioned_before)
		return transitioned_after
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.button_pressed = False
		self.button_released = False
		self.car_detected = False
		self.__time_events[0] = False
		self.__time_events[1] = False
		self.__time_events[2] = False
		self.__time_events[3] = False
	
	
	def __clear_internal_events(self):
		"""Implementation of __clear_internal_events function.
		"""
		self.local_set_led = False
	
	
	def __micro_step(self):
		"""Implementation of __micro_step function.
		"""
		state = self.__state_vector[0]
		if state == self.State.main_region_red:
			self.__main_region_red_react(-1)
		elif state == self.State.main_region_green:
			self.__main_region_green_react(-1)
		elif state == self.State.main_region_yellow:
			self.__main_region_yellow_react(-1)
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		#Performs a 'run to completion' step.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		next_event = self.__get_next_event()
		if next_event is not None:
			self.__execute_queued_event(next_event)
		condition_0 = True
		while condition_0:
			self.__micro_step()
			self.__clear_in_events()
			self.__clear_internal_events()
			condition_0 = False
			next_event = self.__get_next_event()
			if next_event is not None:
				self.__execute_queued_event(next_event)
				condition_0 = True
		self.__is_executing = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		#Activates the state machine.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default enter sequence for statechart Statechart
		self.__enter_sequence_main_region_default()
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		#Deactivates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default exit sequence for statechart Statechart
		self.__exit_sequence_main_region()
		self.__is_executing = False
	
	
	def trigger_without_event(self):
		"""Implementation of triggerWithoutEvent function.
		"""
		self.run_cycle()
	
